package httpapi

// Generated from the official SRD 5.1 spell-list pages (pp. 105-113).
var builderSRDSpellCatalog = []builderSpellCatalogEntry{
	{Name: "Acid Splash", Level: 0, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Chill Touch", Level: 0, Classes: []string{"sorcerer", "warlock", "wizard"}},
	{Name: "Dancing Lights", Level: 0, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Druidcraft", Level: 0, Classes: []string{"druid"}},
	{Name: "Eldritch Blast", Level: 0, Classes: []string{"warlock"}},
	{Name: "Fire Bolt", Level: 0, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Guidance", Level: 0, Classes: []string{"cleric", "druid"}},
	{Name: "Light", Level: 0, Classes: []string{"bard", "cleric", "sorcerer", "wizard"}},
	{Name: "Mage Hand", Level: 0, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Mending", Level: 0, Classes: []string{"bard", "cleric", "druid", "sorcerer", "wizard"}},
	{Name: "Message", Level: 0, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Minor Illusion", Level: 0, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Poison Spray", Level: 0, Classes: []string{"druid", "sorcerer", "warlock", "wizard"}},
	{Name: "Prestidigitation", Level: 0, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Produce Flame", Level: 0, Classes: []string{"druid"}},
	{Name: "Ray of Frost", Level: 0, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Resistance", Level: 0, Classes: []string{"cleric", "druid"}},
	{Name: "Sacred Flame", Level: 0, Classes: []string{"cleric"}},
	{Name: "Shillelagh", Level: 0, Classes: []string{"druid"}},
	{Name: "Shocking Grasp", Level: 0, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Spare the Dying", Level: 0, Classes: []string{"cleric"}},
	{Name: "Thaumaturgy", Level: 0, Classes: []string{"cleric"}},
	{Name: "True Strike", Level: 0, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Vicious Mockery", Level: 0, Classes: []string{"bard"}},
	{Name: "Alarm", Level: 1, Classes: []string{"ranger", "wizard"}},
	{Name: "Animal Friendship", Level: 1, Classes: []string{"bard", "druid", "ranger"}},
	{Name: "Bane", Level: 1, Classes: []string{"bard", "cleric"}},
	{Name: "Bless", Level: 1, Classes: []string{"cleric", "paladin"}},
	{Name: "Burning Hands", Level: 1, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Charm Person", Level: 1, Classes: []string{"bard", "druid", "sorcerer", "warlock", "wizard"}},
	{Name: "Color Spray", Level: 1, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Command", Level: 1, Classes: []string{"cleric", "paladin"}},
	{Name: "Comprehend Languages", Level: 1, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Create or Destroy Water", Level: 1, Classes: []string{"cleric", "druid"}},
	{Name: "Cure Wounds", Level: 1, Classes: []string{"bard", "cleric", "druid", "paladin", "ranger"}},
	{Name: "Detect Evil and Good", Level: 1, Classes: []string{"cleric", "paladin"}},
	{Name: "Detect Magic", Level: 1, Classes: []string{"bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "wizard"}},
	{Name: "Detect Poison and Disease", Level: 1, Classes: []string{"cleric", "druid", "paladin", "ranger"}},
	{Name: "Disguise Self", Level: 1, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Divine Favor", Level: 1, Classes: []string{"paladin"}},
	{Name: "Entangle", Level: 1, Classes: []string{"druid"}},
	{Name: "Expeditious Retreat", Level: 1, Classes: []string{"sorcerer", "warlock", "wizard"}},
	{Name: "Faerie Fire", Level: 1, Classes: []string{"bard", "druid"}},
	{Name: "False Life", Level: 1, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Feather Fall", Level: 1, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Find Familiar", Level: 1, Classes: []string{"wizard"}},
	{Name: "Floating Disk", Level: 1, Classes: []string{"wizard"}},
	{Name: "Fog Cloud", Level: 1, Classes: []string{"druid", "ranger", "sorcerer", "wizard"}},
	{Name: "Goodberry", Level: 1, Classes: []string{"druid", "ranger"}},
	{Name: "Grease", Level: 1, Classes: []string{"wizard"}},
	{Name: "Guiding Bolt", Level: 1, Classes: []string{"cleric"}},
	{Name: "Healing Word", Level: 1, Classes: []string{"bard", "cleric", "druid"}},
	{Name: "Hellish Rebuke", Level: 1, Classes: []string{"warlock"}},
	{Name: "Heroism", Level: 1, Classes: []string{"bard", "paladin"}},
	{Name: "Hideous Laughter", Level: 1, Classes: []string{"bard", "wizard"}},
	{Name: "Hunter's Mark", Level: 1, Classes: []string{"ranger"}},
	{Name: "Identify", Level: 1, Classes: []string{"bard", "wizard"}},
	{Name: "Illusory Script", Level: 1, Classes: []string{"bard", "warlock", "wizard"}},
	{Name: "Inflict Wounds", Level: 1, Classes: []string{"cleric"}},
	{Name: "Jump", Level: 1, Classes: []string{"druid", "ranger", "sorcerer", "wizard"}},
	{Name: "Longstrider", Level: 1, Classes: []string{"bard", "druid", "ranger", "wizard"}},
	{Name: "Mage Armor", Level: 1, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Magic Missile", Level: 1, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Protection from Evil and Good", Level: 1, Classes: []string{"cleric", "paladin", "warlock", "wizard"}},
	{Name: "Purify Food and Drink", Level: 1, Classes: []string{"cleric", "druid", "paladin"}},
	{Name: "Sanctuary", Level: 1, Classes: []string{"cleric"}},
	{Name: "Shield", Level: 1, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Shield of Faith", Level: 1, Classes: []string{"cleric", "paladin"}},
	{Name: "Silent Image", Level: 1, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Sleep", Level: 1, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Speak with Animals", Level: 1, Classes: []string{"bard", "druid", "ranger"}},
	{Name: "Thunderwave", Level: 1, Classes: []string{"bard", "druid", "sorcerer", "wizard"}},
	{Name: "Unseen Servant", Level: 1, Classes: []string{"bard", "warlock", "wizard"}},
	{Name: "Acid Arrow", Level: 2, Classes: []string{"wizard"}},
	{Name: "Aid", Level: 2, Classes: []string{"cleric", "paladin"}},
	{Name: "Alter Self", Level: 2, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Animal Messenger", Level: 2, Classes: []string{"bard", "druid", "ranger"}},
	{Name: "Arcane Lock", Level: 2, Classes: []string{"wizard"}},
	{Name: "Arcanist's Magic Aura", Level: 2, Classes: []string{"wizard"}},
	{Name: "Augury", Level: 2, Classes: []string{"cleric"}},
	{Name: "Barkskin", Level: 2, Classes: []string{"druid", "ranger"}},
	{Name: "Blindness/Deafness", Level: 2, Classes: []string{"bard", "cleric", "sorcerer", "wizard"}},
	{Name: "Blur", Level: 2, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Branding Smite", Level: 2, Classes: []string{"paladin"}},
	{Name: "Calm Emotions", Level: 2, Classes: []string{"bard", "cleric"}},
	{Name: "Continual Flame", Level: 2, Classes: []string{"cleric", "wizard"}},
	{Name: "Darkness", Level: 2, Classes: []string{"sorcerer", "warlock", "wizard"}},
	{Name: "Darkvision", Level: 2, Classes: []string{"druid", "ranger", "sorcerer", "wizard"}},
	{Name: "Detect Thoughts", Level: 2, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Enhance Ability", Level: 2, Classes: []string{"bard", "cleric", "druid", "sorcerer"}},
	{Name: "Enlarge/Reduce", Level: 2, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Enthrall", Level: 2, Classes: []string{"bard", "warlock"}},
	{Name: "Find Steed", Level: 2, Classes: []string{"paladin"}},
	{Name: "Find Traps", Level: 2, Classes: []string{"cleric", "druid", "ranger"}},
	{Name: "Flame Blade", Level: 2, Classes: []string{"druid"}},
	{Name: "Flaming Sphere", Level: 2, Classes: []string{"druid", "wizard"}},
	{Name: "Gentle Repose", Level: 2, Classes: []string{"cleric", "wizard"}},
	{Name: "Gust of Wind", Level: 2, Classes: []string{"druid", "sorcerer", "wizard"}},
	{Name: "Heat Metal", Level: 2, Classes: []string{"bard", "druid"}},
	{Name: "Hold Person", Level: 2, Classes: []string{"bard", "cleric", "druid", "sorcerer", "warlock", "wizard"}},
	{Name: "Invisibility", Level: 2, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Knock", Level: 2, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Lesser Restoration", Level: 2, Classes: []string{"bard", "cleric", "druid", "paladin", "ranger"}},
	{Name: "Levitate", Level: 2, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Locate Animals or Plants", Level: 2, Classes: []string{"bard", "druid", "ranger"}},
	{Name: "Locate Object", Level: 2, Classes: []string{"bard", "cleric", "druid", "paladin", "ranger", "wizard"}},
	{Name: "Magic Mouth", Level: 2, Classes: []string{"bard", "wizard"}},
	{Name: "Magic Weapon", Level: 2, Classes: []string{"paladin", "wizard"}},
	{Name: "Mirror Image", Level: 2, Classes: []string{"sorcerer", "warlock", "wizard"}},
	{Name: "Misty Step", Level: 2, Classes: []string{"sorcerer", "warlock", "wizard"}},
	{Name: "Moonbeam", Level: 2, Classes: []string{"druid"}},
	{Name: "Pass without Trace", Level: 2, Classes: []string{"druid", "ranger"}},
	{Name: "Prayer of Healing", Level: 2, Classes: []string{"cleric"}},
	{Name: "Protection from Poison", Level: 2, Classes: []string{"cleric", "druid", "paladin", "ranger"}},
	{Name: "Ray of Enfeeblement", Level: 2, Classes: []string{"warlock", "wizard"}},
	{Name: "Rope Trick", Level: 2, Classes: []string{"wizard"}},
	{Name: "Scorching Ray", Level: 2, Classes: []string{"sorcerer", "wizard"}},
	{Name: "See Invisibility", Level: 2, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Shatter", Level: 2, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Silence", Level: 2, Classes: []string{"bard", "cleric", "ranger"}},
	{Name: "Spider Climb", Level: 2, Classes: []string{"sorcerer", "warlock", "wizard"}},
	{Name: "Spike Growth", Level: 2, Classes: []string{"druid", "ranger"}},
	{Name: "Spiritual Weapon", Level: 2, Classes: []string{"cleric"}},
	{Name: "Suggestion", Level: 2, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Warding Bond", Level: 2, Classes: []string{"cleric"}},
	{Name: "Web", Level: 2, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Zone of Truth", Level: 2, Classes: []string{"bard", "cleric", "paladin"}},
	{Name: "Animate Dead", Level: 3, Classes: []string{"cleric", "wizard"}},
	{Name: "Beacon of Hope", Level: 3, Classes: []string{"cleric"}},
	{Name: "Bestow Curse", Level: 3, Classes: []string{"bard", "cleric", "wizard"}},
	{Name: "Blink", Level: 3, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Call Lightning", Level: 3, Classes: []string{"druid"}},
	{Name: "Clairvoyance", Level: 3, Classes: []string{"bard", "cleric", "sorcerer", "wizard"}},
	{Name: "Conjure Animals", Level: 3, Classes: []string{"druid", "ranger"}},
	{Name: "Counterspell", Level: 3, Classes: []string{"sorcerer", "warlock", "wizard"}},
	{Name: "Create Food and Water", Level: 3, Classes: []string{"cleric", "paladin"}},
	{Name: "Daylight", Level: 3, Classes: []string{"cleric", "druid", "paladin", "ranger", "sorcerer"}},
	{Name: "Dispel Magic", Level: 3, Classes: []string{"bard", "cleric", "druid", "paladin", "sorcerer", "warlock", "wizard"}},
	{Name: "Fear", Level: 3, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Fireball", Level: 3, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Fly", Level: 3, Classes: []string{"sorcerer", "warlock", "wizard"}},
	{Name: "Gaseous Form", Level: 3, Classes: []string{"sorcerer", "warlock", "wizard"}},
	{Name: "Glyph of Warding", Level: 3, Classes: []string{"bard", "cleric", "wizard"}},
	{Name: "Haste", Level: 3, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Hypnotic Pattern", Level: 3, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Lightning Bolt", Level: 3, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Magic Circle", Level: 3, Classes: []string{"cleric", "paladin", "warlock", "wizard"}},
	{Name: "Major Image", Level: 3, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Mass Healing Word", Level: 3, Classes: []string{"cleric"}},
	{Name: "Meld into Stone", Level: 3, Classes: []string{"cleric", "druid"}},
	{Name: "Nondetection", Level: 3, Classes: []string{"bard", "ranger", "wizard"}},
	{Name: "Phantom Steed", Level: 3, Classes: []string{"wizard"}},
	{Name: "Plant Growth", Level: 3, Classes: []string{"bard", "druid", "ranger"}},
	{Name: "Protection from Energy", Level: 3, Classes: []string{"cleric", "druid", "ranger", "sorcerer", "wizard"}},
	{Name: "Remove Curse", Level: 3, Classes: []string{"cleric", "paladin", "warlock", "wizard"}},
	{Name: "Revivify", Level: 3, Classes: []string{"cleric", "paladin"}},
	{Name: "Sending", Level: 3, Classes: []string{"bard", "cleric", "wizard"}},
	{Name: "Sleet Storm", Level: 3, Classes: []string{"druid", "sorcerer", "wizard"}},
	{Name: "Slow", Level: 3, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Speak with Dead", Level: 3, Classes: []string{"bard", "cleric"}},
	{Name: "Speak with Plants", Level: 3, Classes: []string{"bard", "druid", "ranger"}},
	{Name: "Spirit Guardians", Level: 3, Classes: []string{"cleric"}},
	{Name: "Stinking Cloud", Level: 3, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Tiny Hut", Level: 3, Classes: []string{"bard", "wizard"}},
	{Name: "Tongues", Level: 3, Classes: []string{"bard", "cleric", "sorcerer", "warlock", "wizard"}},
	{Name: "Vampiric Touch", Level: 3, Classes: []string{"warlock", "wizard"}},
	{Name: "Water Breathing", Level: 3, Classes: []string{"druid", "ranger", "sorcerer", "wizard"}},
	{Name: "Water Walk", Level: 3, Classes: []string{"cleric", "druid", "ranger", "sorcerer"}},
	{Name: "Wind Wall", Level: 3, Classes: []string{"druid", "ranger"}},
	{Name: "Arcane Eye", Level: 4, Classes: []string{"wizard"}},
	{Name: "Banishment", Level: 4, Classes: []string{"cleric", "paladin", "sorcerer", "warlock", "wizard"}},
	{Name: "Black Tentacles", Level: 4, Classes: []string{"wizard"}},
	{Name: "Blight", Level: 4, Classes: []string{"druid", "sorcerer", "warlock", "wizard"}},
	{Name: "Compulsion", Level: 4, Classes: []string{"bard"}},
	{Name: "Confusion", Level: 4, Classes: []string{"bard", "druid", "sorcerer", "wizard"}},
	{Name: "Conjure Minor Elementals", Level: 4, Classes: []string{"druid", "wizard"}},
	{Name: "Conjure Woodland Beings", Level: 4, Classes: []string{"druid", "ranger"}},
	{Name: "Control Water", Level: 4, Classes: []string{"cleric", "druid", "wizard"}},
	{Name: "Death Ward", Level: 4, Classes: []string{"cleric", "paladin"}},
	{Name: "Dimension Door", Level: 4, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Divination", Level: 4, Classes: []string{"cleric"}},
	{Name: "Dominate Beast", Level: 4, Classes: []string{"druid", "sorcerer"}},
	{Name: "Fabricate", Level: 4, Classes: []string{"wizard"}},
	{Name: "Faithful Hound", Level: 4, Classes: []string{"wizard"}},
	{Name: "Fire Shield", Level: 4, Classes: []string{"wizard"}},
	{Name: "Freedom of Movement", Level: 4, Classes: []string{"bard", "cleric", "druid", "ranger"}},
	{Name: "Giant Insect", Level: 4, Classes: []string{"druid"}},
	{Name: "Greater Invisibility", Level: 4, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Guardian of Faith", Level: 4, Classes: []string{"cleric"}},
	{Name: "Hallucinatory Terrain", Level: 4, Classes: []string{"bard", "druid", "warlock", "wizard"}},
	{Name: "Ice Storm", Level: 4, Classes: []string{"druid", "sorcerer", "wizard"}},
	{Name: "Locate Creature", Level: 4, Classes: []string{"bard", "cleric", "druid", "paladin", "ranger", "wizard"}},
	{Name: "Phantasmal Killer", Level: 4, Classes: []string{"wizard"}},
	{Name: "Polymorph", Level: 4, Classes: []string{"bard", "druid", "sorcerer", "wizard"}},
	{Name: "Private Sanctum", Level: 4, Classes: []string{"wizard"}},
	{Name: "Resilient Sphere", Level: 4, Classes: []string{"wizard"}},
	{Name: "Secret Chest", Level: 4, Classes: []string{"wizard"}},
	{Name: "Stone Shape", Level: 4, Classes: []string{"cleric", "druid", "wizard"}},
	{Name: "Stoneskin", Level: 4, Classes: []string{"druid", "ranger", "sorcerer", "wizard"}},
	{Name: "Wall of Fire", Level: 4, Classes: []string{"druid", "sorcerer", "wizard"}},
	{Name: "Animate Objects", Level: 5, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Antilife Shell", Level: 5, Classes: []string{"druid"}},
	{Name: "Arcane Hand", Level: 5, Classes: []string{"wizard"}},
	{Name: "Awaken", Level: 5, Classes: []string{"bard", "druid"}},
	{Name: "Cloudkill", Level: 5, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Commune", Level: 5, Classes: []string{"cleric"}},
	{Name: "Commune with Nature", Level: 5, Classes: []string{"druid", "ranger"}},
	{Name: "Cone of Cold", Level: 5, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Conjure Elemental", Level: 5, Classes: []string{"druid", "wizard"}},
	{Name: "Contact Other Plane", Level: 5, Classes: []string{"warlock", "wizard"}},
	{Name: "Contagion", Level: 5, Classes: []string{"cleric", "druid"}},
	{Name: "Creation", Level: 5, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Dispel Evil and Good", Level: 5, Classes: []string{"cleric", "paladin"}},
	{Name: "Dominate Person", Level: 5, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Dream", Level: 5, Classes: []string{"bard", "warlock", "wizard"}},
	{Name: "Flame Strike", Level: 5, Classes: []string{"cleric"}},
	{Name: "Geas", Level: 5, Classes: []string{"bard", "cleric", "druid", "paladin", "wizard"}},
	{Name: "Greater Restoration", Level: 5, Classes: []string{"bard", "cleric", "druid"}},
	{Name: "Hallow", Level: 5, Classes: []string{"cleric"}},
	{Name: "Hold Monster", Level: 5, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Insect Plague", Level: 5, Classes: []string{"cleric", "druid", "sorcerer"}},
	{Name: "Legend Lore", Level: 5, Classes: []string{"bard", "cleric", "wizard"}},
	{Name: "Mass Cure Wounds", Level: 5, Classes: []string{"bard", "cleric", "druid"}},
	{Name: "Mislead", Level: 5, Classes: []string{"bard", "wizard"}},
	{Name: "Modify Memory", Level: 5, Classes: []string{"bard", "wizard"}},
	{Name: "Passwall", Level: 5, Classes: []string{"wizard"}},
	{Name: "Planar Binding", Level: 5, Classes: []string{"bard", "cleric", "druid", "wizard"}},
	{Name: "Raise Dead", Level: 5, Classes: []string{"bard", "cleric", "paladin"}},
	{Name: "Reincarnate", Level: 5, Classes: []string{"druid"}},
	{Name: "Scrying", Level: 5, Classes: []string{"bard", "cleric", "druid", "warlock", "wizard"}},
	{Name: "Seeming", Level: 5, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Telekinesis", Level: 5, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Telepathic Bond", Level: 5, Classes: []string{"wizard"}},
	{Name: "Teleportation Circle", Level: 5, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Tree Stride", Level: 5, Classes: []string{"druid", "ranger"}},
	{Name: "Wall of Force", Level: 5, Classes: []string{"wizard"}},
	{Name: "Wall of Stone", Level: 5, Classes: []string{"druid", "sorcerer", "wizard"}},
	{Name: "Blade Barrier", Level: 6, Classes: []string{"cleric"}},
	{Name: "Chain Lightning", Level: 6, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Circle of Death", Level: 6, Classes: []string{"sorcerer", "warlock", "wizard"}},
	{Name: "Conjure Fey", Level: 6, Classes: []string{"druid", "warlock"}},
	{Name: "Contingency", Level: 6, Classes: []string{"wizard"}},
	{Name: "Create Undead", Level: 6, Classes: []string{"cleric", "warlock", "wizard"}},
	{Name: "Disintegrate", Level: 6, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Eyebite", Level: 6, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Find the Path", Level: 6, Classes: []string{"bard", "cleric", "druid"}},
	{Name: "Flesh to Stone", Level: 6, Classes: []string{"warlock", "wizard"}},
	{Name: "Forbiddance", Level: 6, Classes: []string{"cleric"}},
	{Name: "Freezing Sphere", Level: 6, Classes: []string{"wizard"}},
	{Name: "Globe of Invulnerability", Level: 6, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Guards and Wards", Level: 6, Classes: []string{"bard", "wizard"}},
	{Name: "Harm", Level: 6, Classes: []string{"cleric"}},
	{Name: "Heal", Level: 6, Classes: []string{"cleric", "druid"}},
	{Name: "Heroes' Feast", Level: 6, Classes: []string{"cleric", "druid"}},
	{Name: "Instant Summons", Level: 6, Classes: []string{"wizard"}},
	{Name: "Irresistible Dance", Level: 6, Classes: []string{"bard", "wizard"}},
	{Name: "Magic Jar", Level: 6, Classes: []string{"wizard"}},
	{Name: "Mass Suggestion", Level: 6, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Move Earth", Level: 6, Classes: []string{"druid", "sorcerer", "wizard"}},
	{Name: "Planar Ally", Level: 6, Classes: []string{"cleric"}},
	{Name: "Programmed Illusion", Level: 6, Classes: []string{"bard", "wizard"}},
	{Name: "Sunbeam", Level: 6, Classes: []string{"druid", "sorcerer", "wizard"}},
	{Name: "Transport via Plants", Level: 6, Classes: []string{"druid"}},
	{Name: "True Seeing", Level: 6, Classes: []string{"bard", "cleric", "sorcerer", "warlock", "wizard"}},
	{Name: "Wall of Ice", Level: 6, Classes: []string{"wizard"}},
	{Name: "Wall of Thorns", Level: 6, Classes: []string{"druid"}},
	{Name: "Wind Walk", Level: 6, Classes: []string{"druid"}},
	{Name: "Word of Recall", Level: 6, Classes: []string{"cleric"}},
	{Name: "Arcane Sword", Level: 7, Classes: []string{"bard", "wizard"}},
	{Name: "Conjure Celestial", Level: 7, Classes: []string{"cleric"}},
	{Name: "Delayed Blast Fireball", Level: 7, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Divine Word", Level: 7, Classes: []string{"cleric"}},
	{Name: "Etherealness", Level: 7, Classes: []string{"bard", "cleric", "sorcerer", "warlock", "wizard"}},
	{Name: "Finger of Death", Level: 7, Classes: []string{"sorcerer", "warlock", "wizard"}},
	{Name: "Fire Storm", Level: 7, Classes: []string{"cleric", "druid", "sorcerer"}},
	{Name: "Forcecage", Level: 7, Classes: []string{"bard", "warlock", "wizard"}},
	{Name: "Magnificent Mansion", Level: 7, Classes: []string{"bard", "wizard"}},
	{Name: "Mirage Arcane", Level: 7, Classes: []string{"bard", "druid", "wizard"}},
	{Name: "Plane Shift", Level: 7, Classes: []string{"cleric", "druid", "sorcerer", "warlock", "wizard"}},
	{Name: "Prismatic Spray", Level: 7, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Project Image", Level: 7, Classes: []string{"bard", "wizard"}},
	{Name: "Regenerate", Level: 7, Classes: []string{"bard", "cleric", "druid"}},
	{Name: "Resurrection", Level: 7, Classes: []string{"bard", "cleric"}},
	{Name: "Reverse Gravity", Level: 7, Classes: []string{"druid", "sorcerer", "wizard"}},
	{Name: "Sequester", Level: 7, Classes: []string{"wizard"}},
	{Name: "Simulacrum", Level: 7, Classes: []string{"wizard"}},
	{Name: "Symbol", Level: 7, Classes: []string{"bard", "cleric", "wizard"}},
	{Name: "Teleport", Level: 7, Classes: []string{"bard", "sorcerer", "wizard"}},
	{Name: "Animal Shapes", Level: 8, Classes: []string{"druid"}},
	{Name: "Antimagic Field", Level: 8, Classes: []string{"cleric", "wizard"}},
	{Name: "Antipathy/Sympathy", Level: 8, Classes: []string{"druid", "wizard"}},
	{Name: "Clone", Level: 8, Classes: []string{"wizard"}},
	{Name: "Control Weather", Level: 8, Classes: []string{"cleric", "druid", "wizard"}},
	{Name: "Demiplane", Level: 8, Classes: []string{"warlock", "wizard"}},
	{Name: "Dominate Monster", Level: 8, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Earthquake", Level: 8, Classes: []string{"cleric", "druid", "sorcerer"}},
	{Name: "Feeblemind", Level: 8, Classes: []string{"bard", "druid", "warlock", "wizard"}},
	{Name: "Glibness", Level: 8, Classes: []string{"bard", "warlock"}},
	{Name: "Holy Aura", Level: 8, Classes: []string{"cleric"}},
	{Name: "Incendiary Cloud", Level: 8, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Maze", Level: 8, Classes: []string{"wizard"}},
	{Name: "Mind Blank", Level: 8, Classes: []string{"bard", "wizard"}},
	{Name: "Power Word Stun", Level: 8, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Sunburst", Level: 8, Classes: []string{"druid", "sorcerer", "wizard"}},
	{Name: "Astral Projection", Level: 9, Classes: []string{"cleric", "warlock", "wizard"}},
	{Name: "Foresight", Level: 9, Classes: []string{"bard", "druid", "warlock", "wizard"}},
	{Name: "Gate", Level: 9, Classes: []string{"cleric", "sorcerer", "wizard"}},
	{Name: "Imprisonment", Level: 9, Classes: []string{"warlock", "wizard"}},
	{Name: "Mass Heal", Level: 9, Classes: []string{"cleric"}},
	{Name: "Meteor Swarm", Level: 9, Classes: []string{"sorcerer", "wizard"}},
	{Name: "Power Word Kill", Level: 9, Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
	{Name: "Prismatic Wall", Level: 9, Classes: []string{"wizard"}},
	{Name: "Shapechange", Level: 9, Classes: []string{"druid", "wizard"}},
	{Name: "Storm of Vengeance", Level: 9, Classes: []string{"druid"}},
	{Name: "Time Stop", Level: 9, Classes: []string{"sorcerer", "wizard"}},
	{Name: "True Polymorph", Level: 9, Classes: []string{"bard", "warlock", "wizard"}},
	{Name: "True Resurrection", Level: 9, Classes: []string{"cleric", "druid"}},
	{Name: "Weird", Level: 9, Classes: []string{"wizard"}},
	{Name: "Wish", Level: 9, Classes: []string{"sorcerer", "wizard"}},
}
