#!/usr/bin/env bash

set -euo pipefail

API_BASE_URL="${API_BASE_URL:-http://localhost:8085}"
WEB_BASE_URL="${WEB_BASE_URL:-http://localhost:3005}"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

require_cmd curl
require_cmd jq

echo "==> Health check"
curl -fsS "${API_BASE_URL}/api/health" | jq .

suffix="$(date +%s)"
campaign_name="MVP Campaign ${suffix}"
scene_name="MVP Smoke Scene ${suffix}"
location_name="Test Chamber"
character_name="Smoke Warlock ${suffix}"
player_name="Smoke Player"

echo
echo "==> Create campaign"
campaign_json="$(curl -fsS -X POST "${API_BASE_URL}/api/campaigns" \
  -H 'Content-Type: application/json' \
  -d "$(jq -cn --arg name "${campaign_name}" '{name:$name, description:"Generated by MVP smoke test"}')")"
campaign_id="$(jq -r '.id' <<<"${campaign_json}")"
echo "${campaign_json}" | jq '{id,name}'

echo
echo "==> Create session"
session_json="$(curl -fsS -X POST "${API_BASE_URL}/api/sessions" \
  -H 'Content-Type: application/json' \
  -d "$(jq -cn --arg campaign_id "${campaign_id}" --arg current_scene "${scene_name}" --arg current_location "${location_name}" '{campaign_id:$campaign_id, current_scene:$current_scene, current_location:$current_location, language:"de"}')")"
session_id="$(jq -r '.id' <<<"${session_json}")"
echo "${session_json}" | jq '{id,status,current_scene,current_location}'

echo
echo "==> Start session"
curl -fsS -X POST "${API_BASE_URL}/api/sessions/${session_id}/start" -H 'Content-Type: application/json' -d '{}' | jq '{id,status}'

echo
echo "==> Create character"
character_json="$(curl -fsS -X POST "${API_BASE_URL}/api/characters" \
  -H 'Content-Type: application/json' \
  -d "$(jq -cn --arg name "${character_name}" --arg player_name "${player_name}" '{name:$name, player_name:$player_name, class_and_level:"warlock", race:"half-elf", background:"acolyte", abilities:{strength:8,dexterity:14,constitution:13,intelligence:12,wisdom:10,charisma:15}, metadata:{creation_method:"smoke_test"}}')")"
character_id="$(jq -r '.id' <<<"${character_json}")"
echo "${character_json}" | jq '{id,name,class_and_level,race}'

echo
echo "==> Create player link"
player_link_json="$(curl -fsS -X POST "${API_BASE_URL}/api/sessions/${session_id}/player-links" \
  -H 'Content-Type: application/json' \
  -d "$(jq -cn --arg display_name "${player_name}" --arg character_id "${character_id}" '{display_name:$display_name, character_id:$character_id}')")"
player_slot_id="$(jq -r '.player_slot.id' <<<"${player_link_json}")"
join_url="$(jq -r '.join_url' <<<"${player_link_json}")"
token="${join_url##*/}"
echo "${player_link_json}" | jq '{player_slot:.player_slot.display_name, join_url}'

echo
echo "==> Join player portal"
curl -fsS -X POST "${API_BASE_URL}/api/player-portal/join/${token}" | jq '{token, player_slot:.player_slot.display_name, status:.player_slot.status}'

echo
echo "==> Ask AI DM"
gm_json="$(curl -fsS -X POST "${API_BASE_URL}/api/gm/respond" \
  -H 'Content-Type: application/json' \
  -d "$(jq -cn --arg session_id "${session_id}" '{session_id:$session_id, player_input:"Die Gruppe betritt vorsichtig den Raum und lauscht. Beschreibe die Szene kurz auf Deutsch.", language:"de"}')")"
echo "${gm_json}" | jq '{session_id,prompt_source,raw_model,narration}'

document_id="$(curl -fsS "${API_BASE_URL}/api/documents" | jq -r '.items[0].id // empty')"
asset_id="$(curl -fsS "${API_BASE_URL}/api/assets" | jq -r '.items[0].id // empty')"

if [[ -n "${document_id}" || -n "${asset_id}" ]]; then
  echo
  echo "==> Release visible state to player portal"
  visible_payload="$(jq -cn --arg document_id "${document_id}" --arg asset_id "${asset_id}" '
    {
      handout_document_ids: (if $document_id == "" then [] else [$document_id] end),
      media_asset_ids: (if $asset_id == "" then [] else [$asset_id] end)
    }'
  )"
  curl -fsS -X PUT "${API_BASE_URL}/api/player-slots/${player_slot_id}/visible-state" \
    -H 'Content-Type: application/json' \
    -d "${visible_payload}" | jq '{player_slot_id, visible_handouts, visible_media}'
fi

echo
echo "==> Portal verification"
curl -fsS "${API_BASE_URL}/api/player-portal/me?token=${token}" | jq '{token, player_slot:.player_slot.display_name, visible_handouts:(.visible_state.visible_handouts|length), visible_media:(.visible_state.visible_media|length)}'

echo
echo "==> Useful URLs"
echo "Operator sessions: ${WEB_BASE_URL}/sessions"
echo "Active session:    ${WEB_BASE_URL}/sessions/${session_id}"
echo "Player join:       ${WEB_BASE_URL}/join/${token}"
echo "Player portal:     ${WEB_BASE_URL}/player-portal/${token}"
